### ISSUE TITLE
Unstopped media continues to play after the spawned browser window is closed

### ISSUE THREAD

**Issue by neil-fry** [SafeExamBrowser/seb-mac#214]
While testing we have found that in SEB-Mac if you click on a link that launches a new window containing a video with audio (either a file or a streaming service like Youtube), if you close the window without first stopping the media, the audio continues to play.  In some cases it is possible to re-spawn a window, start the media, stop it and then close the window. In other cases it doesn't work and it is necessary to restart SEB-Mac completely.

I would expect that closing the window would also stop any media from playing. This works as expected in SEB-Windows.

**Steps to reproduce:**

1. Click on link (New windows pops open)
2. Select play on the media player / streaming service (Media begins to play)
3. Close the Window (Media audio continues to play and cannot be stopped)

**Here are some resources for testing:**

Files

[MP4](https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4)

Streaming

[Youtube](https://www.youtube.com/watch?v=tgbNymZ7vqY)

[Vimeo](https://vimeo.com/111625654)

**Comment by danschlet** [comment]
This should be solved in [SEB 3.1](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.1), although it needs to be tested with the classic and modern WebView and the new API used by SEB 3.1 is only available from macOS 11.3 or newer. So it's possible that using the modern WebView this issue will still exist if using an older macOS version than 11.3.

**Comment by neil-fry** [comment]
Hi,
Thanks for look at this. I've tested using the latest SEB 3.1 on MacOS 12.3.1 (M1 Pro) but the issue is not resolved. 
Is there anything else I can do to help?
Neil

**Comment by danschlet** [comment]
Yes, you're right, it still doesn't work when using the modern WebView. Unfortunately your issue report came in after code freeze for SEB 3.1 and I didn't had time to test it anymore. I will work on it and will be contained latest in SEB 3.2 (which is already quite advanced in development).

As a workaround you could use the classic WebView (which of course has disadvantages like being slower and not complying to some modern web APIs) by setting Preferences/ Browser/"Select Browser Engine Policy" to "Force Classic" (key browserWindowWebView = 1).

**Comment by danschlet** [comment]
This issue should be fixed in [SEB 3.1.1pre1](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.1.1pre1).

**Comment by neil-fry** [comment]
Hi Daniel. Sorry for not getting back sooner! I've checked this with 3.1.1pre1 and it looks like it's fixed to me.
Cheers
Neil
