### ISSUE TITLE
Selecting multiple files for upload not working macOS

### ISSUE THREAD

**Issue by Krisell** [SafeExamBrowser/seb-mac#29]
**Steps to reproduce the problem**
Use SEB to go to any page which uses a file input-field with the multiple-attribute, for instance https://smallpdf.com/merge-pdf

**What's the problem**
Multiple files can't be selected.

**What is supposed to happen**
Multiple files should be selectable, using cmd or shift, or dragging mouse. This works as expected in any other browser I've tried, including SEB for Windows.

**Comment by danschlet** [comment]
This is fixed in the final pre-release build of SEB 2.1.4 (will be available in the testing repository later today).

**Comment by Krisell** [comment]
I tried with 2.1.4pre3 (which I guess it not the latest version) and the issue remains. I also noticed another closely related issue that I've not noticed before, or that's been introduced now. The filtering of types based on the "accept-parameter" is not respected. I compared this with Safari outside of SEB which behaves as expected.

**Comment by danschlet** [comment]
Yes, something more urgent came up yesterday and I couldn't work on the last remaining issues. I hope the final build will be available by Monday.

I have to see if the WebKit framework has an API for that accept-attribute. You can't compare everything to Safari, Apple doesn't give developers full access to all WebKit features. I also still have to use WebKit 1 instead of 2 in Safari, as again not all necessary features are supported in the newer WKWebView. And SEB is an exam browser, I don't care if some convenience parameters aren't yet supported if there are way more important features which we need to implement first...

**Comment by Krisell** [comment]
I absolutely understand. It’s by no means criticism, only notes about discrepancies from other browsers and the standard, (what else should I compare against?) and I’m guessing you’d rather have issues reported than obliviously ignored?

**Comment by Krisell** [comment]
I absolutely understand. It’s by no means criticism, only notes about discrepancies from other browsers and the standard, (what else should I compare against?) and I’m guessing you’d rather have issues reported than obliviously ignored?

**Comment by danschlet** [comment]
You're right, better to report even minor issues. We SEB developers sometimes don't even realize that there is something missing (like this argument), as we're desktop/mobile application developers and not web developers. My comment was just meant to explain why not everything in SEB works like in a regular browser and why that we have to set priorities.

**Comment by danschlet** [comment]
The new testing build 2.1.4pre4 with this issue fixes [is now available](https://github.com/SafeExamBrowser/seb-testing/tree/master/mac/2.1.4) (I had to spend some time fixing also the Touch Bar disabling feature).

Unfortunately the classic WebKit framework doesn't seem to offer an API for that accept-attribute. I will look into a possible workaround when implementing the new WebKit (WKWebView).

**Comment by Krisell** [comment]
Thank you, it does work now. Great job!

I also noticed the information about the touch bar not being reset, which I was just about to file a bug report for. Nice!
