### ISSUE TITLE
Prohibited process locked SEB

### ISSUE THREAD

**Issue by lifeunexpected** [SafeExamBrowser/seb-mac#294]
We are having a digital exam today and experiencing a lot of different problems related to "Prohibited Process Locked SEB".

The problems seems to primarly be because Safari is being used because when they use Chrome or another web browser it works correct.

This happens on different versions om macOS and but the students are using SEB 2.1.4 and 2.3.2.

i will update the post if i get what os version and seb version the use and safari version

[](ur
![IMG_0146](https://user-images.githubusercontent.com/36742392/231416202-99613831-1118-47ef-93d6-a10f60c40524.jpg)
![IMG_0147](https://user-images.githubusercontent.com/36742392/231416213-0c1522d3-3da3-4b0a-b92a-4d28514bddaa.jpg)
![IMG_0148](https://user-images.githubusercontent.com/36742392/231416227-689b0a57-3902-4663-ae89-18c288f0cf99.jpg)
![IMG_0153](https://user-images.githubusercontent.com/36742392/231416239-fb5602bf-d03e-44f2-82ae-f989e71a72d0.jpg)
l)

**Comment by danschlet** [comment]
Note: If this issue still happens with SEB 3.2.5 or 3.3, then please search the according SEB log files for this line
`Couldn't terminate app with localized name (error `
and post the full line here (best also the according SEB log file). I need to know the error number which would be listed in the log if SEB cannot terminate that process.

**Comment by danschlet** [comment]
Another workaround to prevent this lock screens for "com.apple.WebKit.Networking" would be to disable the "Active" flag for the default preset prohibited process "Safari/WebKit Networking". This isn't preferable, as then students could use Safari or other WebKit-based browsers in the background to for example run some web-based screen sharing or video/audio conferencing tool. 

All of this is efficiently prevented with the AAC lockdown mode, that's why that would be the way to go forward in future.

**Comment by uollaswar** [comment]
Hello i have a similar problem, i tried ANY workaround, even factory reset my MAC, still giving the same error... I don't know what to do now, any idea is welcome.
![17048762458248330277991873659457](https://github.com/SafeExamBrowser/seb-mac/assets/71643611/4ae41b01-2ba4-434c-a03e-5a66e4bb7795)

**Comment by lmBored** [comment]
> Note: If this issue still happens with SEB 3.2.5 or 3.3, then please search the according SEB log files for this line `Couldn't terminate app with localized name (error ` and post the full line here (best also the according SEB log file). I need to know the error number which would be listed in the log if SEB cannot terminate that process.
> 
> Also see this issue: #320

I also got this error, this is my log file:
```
2024/01/16 16:15:26:665  BrowserWindow <SEBBrowserWindow: 0x140f661c0>: Title of current Page: Safe Exam Browser 3.2.5  —  Digital test · On-campus test 4
2024/01/16 16:19:17:482  Started application with bundle ID: (null)
2024/01/16 16:19:18:362  Started application with bundle ID: com.apple.textkit.nsattributedstringagent
2024/01/16 16:19:18:462  Couldn't terminate app with localized name (error -1): com.apple.WebKit.Networking, bundle or executable URL: file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/
2024/01/16 16:19:18:462  -[SEBOSXLockedViewController setLockdownAlertTitle:Message:]: Prohibited Process Locked SEB!: SEB is locked because a process, which isn't allow to run cannot be terminated. Enter the quit/unlock password or response, which usually exam supervision/support knows.
2024/01/16 16:19:18:462  Prohibited processes detected: (
        {
        PID = 37060;
        URL = "file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/";
        bundleID = "com.apple.WebKit.Networking";
        name = "com.apple.WebKit.Networking";
    }
)
2024/01/16 16:19:18:464  openLockdownWindows: didLockSEBTime 2024-01-16 15:19:18 +0000, didBecomeActiveTime 2024-01-16 15:19:18 +0000
2024/01/16 16:19:18:464  Locking SEB with red frontmost covering windows
2024/01/16 16:19:18:464  -[SEBController openCoveringWindows]
2024/01/16 16:19:18:464  Screen is active, device description: {
    NSDeviceBitsPerSample = 8;
    NSDeviceColorSpaceName = NSCalibratedRGBColorSpace;
    NSDeviceIsScreen = YES;
    NSDeviceResolution = "NSSize: {144, 144}";
    NSDeviceSize = "NSSize: {1470, 956}";
    NSScreenNumber = 1;
}
2024/01/16 16:19:18:464  Opening lockdown alert covering window with frame {
    Height = 956;
    Width = 1470;
    X = 0;
    Y = 0;
} and window level 1000
2024/01/16 16:19:18:465  Cap window <CapWindowController: 0x1413ae010> init.
2024/01/16 16:19:18:466  BrowserWindow <SEBBrowserWindow: 0x140f661c0> did resign key
2024/01/16 16:19:18:466  Current key window: <CapWindow: 0x28ff648c0> with title 
2024/01/16 16:19:18:500  -[SEBLockedViewController appendErrorString:withTime:]: Prohibited processes detected: (
        {
        PID = 37060;
        URL = "file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/";
        bundleID = "com.apple.WebKit.Networking";
        name = "com.apple.WebKit.Networking";
    }
)
 2024-01-16 16:19:18  
2024/01/16 16:19:18:502  Log scroll view <NSScrollView: 0x14405da00> frame: {
    Height = 378;
    Width = 458;
    X = 0;
    Y = 0;
}, y coordinate to scroll to: 0.000000
2024/01/16 16:19:18:502  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:19:18:808  Started application with bundle ID: (null)
2024/01/16 16:19:30:456  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:19:30:456  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:19:44:203  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:20:00:450  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:20:11:955  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:20:13:449  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:20:31:956  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:20:31:956  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:21:08:957  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:21:08:957  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:21:22:785  Password entered in lock view alert
2024/01/16 16:21:22:786  -[SEBLockedViewController appendErrorString:withTime:]: Correct password entered
 2024-01-16 16:21:22  
```
```
2024/01/16 16:21:22:800  BrowserWindow <SEBBrowserWindow: 0x140f661c0> did become key
2024/01/16 16:21:22:801  Opening info HUD: SEB was locked (exam interrupted) for 2:04 (minutes:seconds)
2024/01/16 16:21:27:698  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:21:52:456  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:29:15:125  Started application with bundle ID: (null)
2024/01/16 16:29:16:030  Started application with bundle ID: com.apple.textkit.nsattributedstringagent
2024/01/16 16:29:16:127  Couldn't terminate app with localized name (error -1): com.apple.WebKit.Networking, bundle or executable URL: file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/
2024/01/16 16:29:16:127  openLockdownWindows: didLockSEBTime 2024-01-16 15:29:16 +0000, didBecomeActiveTime 2024-01-16 15:29:16 +0000
2024/01/16 16:29:16:127  Locking SEB with red frontmost covering windows
2024/01/16 16:29:16:127  -[SEBController openCoveringWindows]
2024/01/16 16:29:16:128  Screen is active, device description: {
    NSDeviceBitsPerSample = 8;
    NSDeviceColorSpaceName = NSCalibratedRGBColorSpace;
    NSDeviceIsScreen = YES;
    NSDeviceResolution = "NSSize: {144, 144}";
    NSDeviceSize = "NSSize: {1470, 956}";
    NSScreenNumber = 1;
}
2024/01/16 16:29:16:128  Opening lockdown alert covering window with frame {
    Height = 956;
    Width = 1470;
    X = 0;
    Y = 0;
} and window level 1000
2024/01/16 16:29:16:129  Cap window <CapWindowController: 0x141110fd0> init.
2024/01/16 16:29:16:129  BrowserWindow <SEBBrowserWindow: 0x140f661c0> did resign key
2024/01/16 16:29:16:129  Current key window: <CapWindow: 0x2a52ddf10> with title 
2024/01/16 16:29:16:162  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:29:16:388  Started application with bundle ID: (null)
2024/01/16 16:29:32:947  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:29:39:450  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:29:46:332  Started application with bundle ID: (null)
2024/01/16 16:29:56:955  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:29:56:955  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:30:18:240  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:30:18:240  Started application with bundle ID: com.apple.WebKit.WebContent
2024/01/16 16:30:23:336  Password entered in lock view alert
2024/01/16 16:30:23:337  -[SEBLockedViewController appendErrorString:withTime:]: Correct password entered
 2024-01-16 16:30:23
```

And I got this image:

> ![IMG_0153](https://user-images.githubusercontent.com/36742392/231416239-fb5602bf-d03e-44f2-82ae-f989e71a72d0.jpg)

**Comment by danschlet** [comment]
This issue seems to finally be fixed in SEB 3.3.2. Please update, we don't recommend still using 3.2.5.

**Comment by lmBored** [comment]
This issue has not been fixed. I've just opened SEB today and still get that red screen. My SEB version is 3.3.2 and Im using MacOS Sonoma 14.2.1

<img width="582" alt="image" src="https://github.com/SafeExamBrowser/seb-mac/assets/79646021/63f28d83-6231-4235-b629-668a76e49c1b">

**Comment by lmBored** [comment]
@danschlet could you have a look please? Im going to have some exams on SEB really soon.

**Comment by danschlet** [comment]
This seems to be an issue on your Mac, as we didn't get new similar reports yet. The improved logging in SEB 3.3.2 shows the error "Operation not permitted" when trying to terminate the offending WebKit process. The reason is likely because it's a system process.

But the question is why SEB wants to terminate this process. In the logs before what you posted it should be mentioned.

Are you using a Hackintosh (macOS on a Windows machine) or some other manipulation of macOS? Could even be a malware which manipulated your system.

**Comment by lmBored** [comment]
> This seems to be an issue on your Mac, as we didn't get new similar reports yet. The improved logging in SEB 3.3.2 shows the error "Operation not permitted" when trying to terminate the offending WebKit process. The reason is likely because it's a system process.
> 
> But the question is why SEB wants to terminate this process. In the logs before what you posted it should be mentioned.
> 
> Are you using a Hackintosh (macOS on a Windows machine) or some other manipulation of macOS? Could even be a malware which manipulated your system.

No, I have a Macbook Air, and I don't think I downloaded any malware as I always download through a package manager and check every thing I download thoroughly. Do you know any other ways to identify the root of this problem?

**Comment by danschlet** [comment]
As I said, post your full log file (log level debug necessary). Before the part what you posted should be the reason why SEB tried to terminate the WebKit process.

Does your user have admin rights? Otherwise try it with a user which has admin rights.

You can also boot your Mac in Safe Mode and try it again.

**Comment by lmBored** [comment]
Here's my full log file, almost everything before that are just seb terminating microsoft app helper:

[org.safeexambrowser.SafeExamBrowser 2024-02-19--19-09-16-368.log](https://github.com/SafeExamBrowser/seb-mac/files/14341861/org.safeexambrowser.SafeExamBrowser.2024-02-19--19-09-16-368.log)

**Comment by danschlet** [comment]
There is a process with the name "nsattributedstringagent Networking" and the bundle ID "com.apple.WebKit.Networking" running on your system, which SEB cannot terminate due to "Operation not permitted", which usually would happen when that process was started by another user (can be a system user, in my case there is a "nsattributedstringagent" process started by a user "_softwareupdate", which obviously is a system process).

 "com.apple.WebKit.Networking"  is one of the preset default prohibited processes in SEB. If you switch this off in your settings ("active" property for this prohibited process needs to be disabled"), SEB would not attempt to terminate this process. But then WebKit-based tools and browsers (Safari, Safari Technology Preview etc.) could be potentially used for cheating. Another option is to use the AAC Assessment Mode instead of the default SEB lockdown (kiosk) mode. 

But I see you're using ANS, so they would need to change their settings.

But again the question is why there is a "nsattributedstringagent Networking" process running on your Mac and also usually processes running under another user don't show their Bundle ID, therefore it should be safe for SEB to terminate all processes with the Bundle ID  "com.apple.WebKit.Networking". So try to quit all applications before running the SEB exam or boot in Safe Mode and start only SEB. You can also try to create a new, separate user account on your Mac for exams and don't change significant system settings and don't install any third party tools which theoretically could cause such issues.

**Comment by lmBored** [comment]
Thank you so much for the help! I will follow your guide!

**Comment by lmBored** [comment]
> There is a process with the name "nsattributedstringagent Networking" and the bundle ID "com.apple.WebKit.Networking" running on your system, which SEB cannot terminate due to "Operation not permitted", which usually would happen when that process was started by another user (can be a system user, in my case there is a "nsattributedstringagent" process started by a user "_softwareupdate", which obviously is a system process).
> 
> "com.apple.WebKit.Networking" is one of the preset default prohibited processes in SEB. If you switch this off in your settings ("active" property for this prohibited process needs to be disabled"), SEB would not attempt to terminate this process. But then WebKit-based tools and browsers (Safari, Safari Technology Preview etc.) could be potentially used for cheating. Another option is to use the AAC Assessment Mode instead of the default SEB lockdown (kiosk) mode.
> 
> But I see you're using ANS, so they would need to change their settings.
> 
> But again the question is why there is a "nsattributedstringagent Networking" process running on your Mac and also usually processes running under another user don't show their Bundle ID, therefore it should be safe for SEB to terminate all processes with the Bundle ID "com.apple.WebKit.Networking". So try to quit all applications before running the SEB exam or boot in Safe Mode and start only SEB. You can also try to create a new, separate user account on your Mac for exams and don't change significant system settings and don't install any third party tools which theoretically could cause such issues.

Hi, user "_softwareupdate" also starts "nsattributedstringagent" process in my case, but `kill -9` doesn't seem to be able to kill this process. Could you update seb to do `sudo kill -9` instead please?

(this is me trying to kill the process)
```
~                                                                                                                                                      
❯ ps aux | grep nsattributedstringagent
_softwareupdate  85551   0.0  0.3 410681712  49504   ??  Ss   10:07PM   0:05.10 /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/XPCServices/nsattributedstringagent.xpc/Contents/MacOS/nsattributedstringagent

~                                                                                                                                                       
❯ kill -9 85551
kill: kill 85551 failed: operation not permitted
```

**Comment by lmBored** [comment]
Could you guide me further on how to use AAC mode? I only need to click "prefer AAC" in the settings right? And if so, do I also have to check the DNS pre-pinning box?

**Comment by HilmanKhairr** [comment]
hi, i'm using 3.3.2 and still facing the issue. anyone can help, please?

here's the log
[org.safeexambrowser.SafeExamBrowser.2024-02-19--19-09-16-368.log](https://github.com/SafeExamBrowser/seb-mac/files/14752127/org.safeexambrowser.SafeExamBrowser.2024-02-19--19-09-16-368.log)

**Comment by HilmanKhairr** [comment]
hi, i'm using 3.3.2 and still facing this issue. anyone can help?

here's the log
`2024/03/26 08:21:13:621  Started application with bundle ID: (null)
2024/03/26 08:21:15:991  Started application with bundle ID: com.apple.textkit.nsattributedstringagent
2024/03/26 08:21:16:321  Couldn't terminate app with localized name (error -1): com.apple.WebKit.Networking, bundle or executable URL: file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/
2024/03/26 08:21:16:321  -[SEBOSXLockedViewController setLockdownAlertTitle:Message:]: Prohibited Process Locked SEB!: SEB is locked because a process, which isn't allow to run cannot be terminated. Enter the quit/unlock password, which usually exam supervision/support knows.
2024/03/26 08:21:16:322  Prohibited processes detected: (
        {
        PID = 2009;
        URL = "file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/";
        bundleID = "com.apple.WebKit.Networking";
        name = "com.apple.WebKit.Networking";
    }
)
2024/03/26 08:21:16:322  openLockdownWindows: didLockSEBTime 2024-03-26 01:21:16 +0000, didBecomeActiveTime 2024-03-26 01:21:16 +0000
2024/03/26 08:21:16:322  Locking SEB with red frontmost covering windows
2024/03/26 08:21:16:322  -[SEBController openCoveringWindows]
2024/03/26 08:21:16:322  Screen is active, device description: {
    NSDeviceBitsPerSample = 8;
    NSDeviceColorSpaceName = NSCalibratedRGBColorSpace;
    NSDeviceIsScreen = YES;
    NSDeviceResolution = "NSSize: {144, 144}";
    NSDeviceSize = "NSSize: {1440, 900}";
    NSScreenNumber = 69733824;
}
2024/03/26 08:21:16:323  Opening lockdown alert covering window with frame {
    Height = 900;
    Width = 1440;
    X = 0;
    Y = 0;
} and window level 1000
2024/03/26 08:21:16:325  Cap window <CapWindowController: 0x6000023b58c0> init.
2024/03/26 08:21:16:325  BrowserWindow <SEBBrowserWindow: 0x7fd23ab4c2b0> did resign key
2024/03/26 08:21:16:325  Current key window: <CapWindow: 0x7fd23ab68150> with title 
2024/03/26 08:21:16:376  -[SEBLockedViewController appendErrorString:withTime:configKey:]: Prohibited processes detected: (
        {
        PID = 2009;
        URL = "file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/";
        bundleID = "com.apple.WebKit.Networking";
        name = "com.apple.WebKit.Networking";
    }
)
 2024-03-26 08:21:16  
2024/03/26 08:21:16:385  Log scroll view <NSScrollView: 0x7fd23588fa00> frame: {
    Height = 378;
    Width = 458;
    X = 0;
    Y = 0;
}, y coordinate to scroll to: 0.000000`

**Comment by HilmanKhairr** [comment]
hi, i'm using 3.3.2 but this issue still happened. anyone can help, please???

> 2024/03/26 08:15:13:934  Cap window <CapWindowController: 0x6000023a20a0> init.
2024/03/26 08:15:13:935  [SEBDockController adjustDock]
2024/03/26 08:15:13:935  -[SEBController adjustModalAlertWindowLevels:] allowSwitchToThirdPartyApps: 0
2024/03/26 08:15:13:935  -[SEBController changeWindowLevels:] allowApps: 0
2024/03/26 08:15:13:935  -[SEBOSXBrowserController browserWindowsChangeLevelAllowApps:] allowApps: 0
2024/03/26 08:15:13:935  -[SEBOSXBrowserController setLevelForBrowserWindow:elevateLevels:] browserWindow: <SEBBrowserWindow: 0x7fd23ab4c2b0> elevateLevels: 1
2024/03/26 08:15:13:937  -[SEBController adjustModalAlertWindowLevels:] allowSwitchToThirdPartyApps: 0
2024/03/26 08:15:14:034  Started application with bundle ID: com.apple.appkit.xpc.openAndSavePanelService
2024/03/26 08:15:14:460  Started application with bundle ID: com.apple.quicklook.QuickLookUIService
2024/03/26 08:15:16:804  BrowserWindow <SEBBrowserWindow: 0x7fd23ab4c2b0>: Title of current Page: Safe Exam Browser 3.3  —  Exam | Telkom ACI
2024/03/26 08:21:13:621  Started application with bundle ID: (null)
2024/03/26 08:21:15:991  Started application with bundle ID: com.apple.textkit.nsattributedstringagent
2024/03/26 08:21:16:321  Couldn't terminate app with localized name (error -1): com.apple.WebKit.Networking, bundle or executable URL: file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/
2024/03/26 08:21:16:321  -[SEBOSXLockedViewController setLockdownAlertTitle:Message:]: Prohibited Process Locked SEB!: SEB is locked because a process, which isn't allow to run cannot be terminated. Enter the quit/unlock password, which usually exam supervision/support knows.
2024/03/26 08:21:16:322  Prohibited processes detected: (
        {
        PID = 2009;
        URL = "file:///System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/";
        bundleID = "com.apple.WebKit.Networking";
        name = "com.apple.WebKit.Networking";
    }
)


>

**Comment by danschlet** [comment]
> Could you guide me further on how to use AAC mode? I only need to click "prefer AAC" in the settings right? And if so, do I also have to check the DNS pre-pinning box?

In such cases search either the [SEB for macOS manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html) or [release notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html). In release notes when searching for the text "AAC", you would have found:

Added DNS pre-pinning when using AAC on macOS <12.1, according to new setting aacDnsPrePinning (Preferences / Security / Use AAC with DNS pre-pinning). SEB will then resolve all domains from settings Start URL and URL filter Allow rules before activating AAC (as in macOS <12.1 DNS lookup during AAC doesn't work). You can define allow rules and if you don't actually need URL filtering, deactivate it afterwards (Preferences / Network / Activate URL filtering) or deactivate single URL filter rules with its Active property. To ensure that DNS lookup works for your web application, you need to add all domains and subdomains as Allow filter rules (don't forget for example domains which are contacted for single-sign-on). Note: Without activating the setting aacDnsPrePinning (Preferences / Security / Use AAC with DNS pre-pinning), AAC will only be used on macOS Catalina 10.15.4 and >=10.15.6 and macOS Monterey 12.1 or newer (not on macOS Big Sur 11.0 - Monterey 12.0). If you want to enforce the use of AAC on all these systems, you either need to use the Use AAC with DNS pre-pinning setting or enforce that only macOS 12.1 or newer is used (Preferences / Security / Allow running from macOS version / Check full macOS version number / enter 12 for Major version number and 1 for Minor version number).

**Comment by danschlet** [comment]
If you need to support also older macOS versions than macOS 10.15 or AAC doesn't work for some of your students because the use macOS 11 and the pre-pinning feature is too complicated to set up for your web application (or you don't want to use AAC for other reasons):

- Deactivate the Safari/WebKit Networking (Identifier: _com.apple.WebKit.Networking_) [prohibited process](https://safeexambrowser.org/macosx/mac_usermanual_en.html#ProhibitedProcessesSection) in your settings (read the manual if you don't understand preset default prohibited processes and how to deactivate them).
- Add a prohibited process for Safari (Identifier: _com.apple.Safari_) and Safari Technology Preview (_com.apple.SafariTechnologyPreview_).

**Comment by lmBored** [comment]
> > Could you guide me further on how to use AAC mode? I only need to click "prefer AAC" in the settings right? And if so, do I also have to check the DNS pre-pinning box?
> 
> In such cases search either the [SEB for macOS manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html) or [release notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html). In release notes when searching for the text "AAC", you would have found:
> 
> Added DNS pre-pinning when using AAC on macOS <12.1, according to new setting aacDnsPrePinning (Preferences / Security / Use AAC with DNS pre-pinning). SEB will then resolve all domains from settings Start URL and URL filter Allow rules before activating AAC (as in macOS <12.1 DNS lookup during AAC doesn't work). You can define allow rules and if you don't actually need URL filtering, deactivate it afterwards (Preferences / Network / Activate URL filtering) or deactivate single URL filter rules with its Active property. To ensure that DNS lookup works for your web application, you need to add all domains and subdomains as Allow filter rules (don't forget for example domains which are contacted for single-sign-on). Note: Without activating the setting aacDnsPrePinning (Preferences / Security / Use AAC with DNS pre-pinning), AAC will only be used on macOS Catalina 10.15.4 and >=10.15.6 and macOS Monterey 12.1 or newer (not on macOS Big Sur 11.0 - Monterey 12.0). If you want to enforce the use of AAC on all these systems, you either need to use the Use AAC with DNS pre-pinning setting or enforce that only macOS 12.1 or newer is used (Preferences / Security / Allow running from macOS version / Check full macOS version number / enter 12 for Major version number and 1 for Minor version number).

Wait to ensure we are on the same page, can I tick "prefer AAC" in SEB settings as a student taking the test or do I need to be the examiner to do that?

**Comment by danschlet** [comment]
Only the examiner/exam administrator can change the settings of their exam. That's why we [always point out](https://safeexambrowser.org/support_en.html) that students should contact their exam provider/examiner, not us. We provide the software for free download without anybody having to register or getting a license. We often don't have an idea what exam system is used with SEB. So we're really not the right ones to ask when students have issues starting an exam. Our support is actually only meant for exam system administrators/providers/examiners/teachers which want to know how to correctly configure SEB...

**Comment by danschlet** [comment]
This should be fixed in [SEB 3.3.3 for macOS](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.3.3). Please test and report if it works for you.
